### PR TITLE
Use CrossModuleBase

### PR DESCRIPTION
**Pull request by joan38**

### CODE REVIEW

**Comment by joan38** [comment]
@DavidGregory084 Can we publish the next version of this?

**Comment by joan38** [comment]
@DavidGregory084 I'm bumping this up as we are looking to upgrade to Mill 0.10.0 ASAP.
Thanks

**Comment by joan38** [comment]
@DavidGregory084 any news?

**Comment by DavidGregory084** [comment]
@joan38 I have been flat out on UK transit projects at work so I have not had time for open source for a while. Sorry about that.

I've done a few things:
* Renamed the `master` branch to `main` - you should just be able to `git fetch` and then switch to the new branch on your local checkout
* Switched to Github Actions for CI and publishing
* Setup automatic Sonatype publishing when release tags are pushed. You are a collaborator in this repository so you should be able to push tags. It's incredibly awkward to make Github Actions run a job only when a tag is pushed to `main` so please be careful only to push version tags to `main`. 😆

**Comment by DavidGregory084** [comment]
Oh yeah and most importantly 0.3.0 is on its way to Sonatype!

**Pull request merged**
