### PR TITLE
Support mill 0.9.x

### PR DESCRIPTION
**Pull request by joan38**
This is awaiting https://github.com/lefou/mill-integrationtest/pull/41

### CODE REVIEW

**Comment by joan38** [comment]
@DavidGregory084 can we have this published?

**Comment by DavidGregory084** [comment]
Yep that should be available shortly @joan38, thanks!

**Comment by joan38** [comment]
Thanks @DavidGregory084.
For some reason it didn't hit maven central yet. Should we wait more or something is missing?

**Comment by DamianReeves** [comment]
Still not there. Is there an issue?

**Comment by DavidGregory084** [comment]
It appears that the staging repository didn't get released correctly - I've released it manually in the Sonatype UI now so it should sync shortly but I will take a look tomorrow and maybe have another go if not

**Comment by joan38** [comment]
It's all good now

**Pull request merged**
